<?xml version="1.0"?>
<package format="3">
  <name>global_planner</name>
  <version>0.1.0</version>
  <description>A* Global Planner — step-by-step ROS2 project</description>
  <maintainer email="dev@example.com">dev</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
